data:
  class_path: pyad.datamanager.TabularDataset
  init_args:
    batch_size: 1024
    data_dir: data\IDS2017\ids2017.csv
    scaler: minmax
    labels_col_name: Category
    normal_str_repr: Benign
    binary_labels_col_name: Label